#!/bin/sh

### BEGIN INIT INFO
# Provides:          ltechagent
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: LabTech remote agent
# Description:       LabTech remote agent
### END INIT INFO

pid_file="/var/run/ltechagent.pid"

get_pid()
{
    cat "$pid_file"
}

is_running()
{
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running
    then
        echo "Already started."
    else
        echo "Starting ltechagent."

        cd /usr/local/ltechagent
        ./ltechagent > /dev/null 2>&1 &

        echo $! > "$pid_file"

        if ! is_running
        then
            echo "Failed to start ltechagent."
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running
    then
        echo -n "Stopping ltechagent.."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running
            then
                break
            fi

            echo -n "."
            sleep 1
        done

        echo

        if is_running
        then
            echo "Failed to stop ltechagent."
            exit 1
        else
            echo "Stopped."
            rm -f "$pid_file"
        fi
    else
        echo "Not running."
    fi
    ;;
esac

exit 0
